### ISSUE TITLE
RTE for VT420 telnet protocol

### ISSUE THREAD

**Issue by tmj1223** [Blazemeter/RTEPlugin#5]
Dear team: Could you improve this plugin to support telnet protocol VT420.My project need this function to do perfomance test

**Comment by rabelenda** [comment]
Thank you for manifesting your interest, we will put it in our backlog. Anyone interested in this support please add a comment or some kind of feedback so we can better prioritize implementing such support.

**Comment by Baraujo25** [comment]
Hi @tmj1223 !
Due to the interests of several users we have started to implement support for VT420 and its later versions. It would be incredibly helpful if you could send us some TCP traffic of any VT420 mainframe application.  
We will convert that traffic into VT420 flow using [wiresham](https://github.com/abstracta/wiresham), to later on be used for testing purposes. 
In order to generate the traffic you should start listening with [wireshark](https://www.wireshark.org/) while you interact with your mainframe application. 
As mentioned before, we will use those dumps for testing purposes, therefore if you consider that the flow contains sensitive data you can obfuscate/modify (e.g replacing the server ip with 0.0.0.0 and any sensitive screen or input bytes with E7, you can get an idea what each byte is by checking each packet in wireshark interface).

If you need any help capturing the packets with wireshark let us know !

Kind regards.

**Comment by Baraujo25** [comment]
Hi @tmj1223,

We could manage to implement support for VT420 on our RTE-Plugin. 

The VT420 protocol is not only supported for manual scripting, but it is also supported for the recorder. 
Now you can just interact with your VT420 Mainframe Application as you normally do and, record every step for performance testing!

New version available on [Plugins Manager](https://jmeter-plugins.org/install/Install/) as always.

Additionally, if you like to install it manually, here are the steps:

1. Go to [RTE-Plugin release v3.1](https://github.com/Blazemeter/RTEPlugin/releases/tag/v3.1) 
1. Download all the jar files on that release.
1. Place the **jmeter-bzm-rte-3.1.jar** on your _JMETER_HOME/lib/ext_
1. Place the other jars on _JMETER_HOME/lib_
1. Run JMeter, enjoy your testing!

**NOTE:** Make sure you do not have duplicated libraries. If that happens, the plugin will not work properly. I would recommend you to use a fresh new JMeter.



It would be nice to hear back from you. Feedback would be awesome!

Best regards,
Joaquin.
